name: Build and Deploy Website
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Deploy Website
    name: Build Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # Checkout code first using https://github.com/actions/checkout
      # Use fetch-depth: 1, to shallow clone your repository
      # , or copy only the latest version of your repository
      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      # List the files in the repo
      - name: List the files in the repo
        run: ls -al
        
        
        
        
        
        
       
